### ISSUE TITLE
Image 元素下的辅助方法 `load` 希望增加示例

### ISSUE THREAD

**Issue by GuoJikun** [leaferjs/docs#1]
https://www.leaferjs.com/ui/reference/display/Image.html#load   
`load` 这个辅助方法不知道来自于哪？怎么用？希望增加示例

**Comment by leaferjs** [comment]
有一些用户需要在Image没添加到页面之前获取图片的宽高，所以才增加了这个手动加载的方法，Image默认是需要添加到页面中才会自动加载的。

**Comment by GuoJikun** [comment]
我已经知道他的作用了，昨天你在群里回复过我了。

```js
const img = new Image({url: "https://**.com/a.png"});
img.load();

const {width, height} = img;
console.log(width, height);
```

应该是这么用的吧！
